<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<div>
	<table>
		<c:choose>
			<c:when test="${not empty detailInfoes}">
				<c:forEach var="info" items="${detailInfoes}">
					<tr>
						<td>객실코드</td>
						<td>${info.roomcode}</td>
					</tr>
					<tr>
						<td>객실명칭</td>
						<td>${info.roomtitle}</td>
					</tr>
					<tr>
						<td>객실크기(평)</td>
						<td>${info.roomsize1}</td>
					</tr>
					<tr>
						<td>객실수</td>
						<td>${info.roomcount}</td>
					</tr>
					<tr>
						<td>기준인원</td>
						<td>${info.roombasecount}</td>
					</tr>
					<tr>
						<td>최대인원</td>
						<td>${info.roommaxcount}</td>
					</tr>
					<tr>
						<td>비수기주중최소</td>
						<td>${info.roomoffseasonminfee1}</td>
					</tr>
					<tr>
						<td>비수기주말최소</td>
						<td>${info.roomoffseasonminfee2}</td>
					</tr>
					<tr>
						<td>성수기주중최소</td>
						<td>${info.roompeakseasonminfee1}</td>
					</tr>
					<tr>
						<td>성수기주말최소</td>
						<td>${info.roompeakseasonminfee2}</td>
					</tr>
					<tr>
						<td>객실소개</td>
						<td>${info.roomintro}</td>
					</tr>
					<tr>
						<td>목욕시설</td>
						<td>${info.roombathfacility}</td>
					</tr>
					<tr>
						<td>욕조</td>
						<td>${info.roombath}</td>
					</tr>
					<tr>
						<td>홈시어터</td>
						<td>${info.roomhometheater}</td>
					</tr>
					<tr>
						<td>에어컨</td>
						<td>${info.roomaircondition}</td>
					</tr>
					<tr>
						<td>TV</td>
						<td>${info.roomtv}</td>
					</tr>
					<tr>
						<td>PC</td>
						<td>${info.roompc}</td>
					</tr>
					<tr>
						<td>케이블설치</td>
						<td>${info.roomcable}</td>
					</tr>
					<tr>
						<td>인터넷</td>
						<td>${info.roominternet}</td>
					</tr>
					<tr>
						<td>냉장고</td>
						<td>${info.roomrefrigerator}</td>
					</tr>
					<tr>
						<td>세면도구</td>
						<td>${info.roomtoiletries}</td>
					</tr>
					<tr>
						<td>소파</td>
						<td>${info.roomsofa}</td>
					</tr>
					<tr>
						<td>취사용품</td>
						<td>${info.roomcook}</td>
					</tr>
					<tr>
						<td>테이블</td>
						<td>${info.roomTable}</td>
					</tr>
					<tr>
						<td>드라이기</td>
						<td>${info.roomhairdryer}</td>
					</tr>
					<tr>
						<td>객실크기(평방미터)</td>
						<td>${info.roomsize2}</td>
					</tr>
					<tr>
						<td>객실사진1</td>
						<td><img alt="${info.roomimg1alt}" src="${info.roomimg1}"> </td>
					</tr>
					<tr>
						<td>객실사진2</td>
						<td><img alt="${info.roomimg2alt}" src="${info.roomimg2}"> </td>
					</tr>
					<tr>
						<td>객실사진3</td>
						<td><img alt="${info.roomimg3alt}" src="${info.roomimg3}"> </td>
					</tr>
					<tr>
						<td>객실사진4</td>
						<td><img alt="${info.roomimg4alt}" src="${info.roomimg4}"> </td>
					</tr>
					<tr>
						<td>객실사진5</td>
						<td><img alt="${info.roomimg5alt}" src="${info.roomimg5}"> </td>
					</tr>
				</c:forEach>
			</c:when>
			<c:when test="${not empty detailInfo}">
					<tr>
						<td>객실코드</td>
						<td>${detailInfo.roomcode}</td>
					</tr>
					<tr>
						<td>객실명칭</td>
						<td>${detailInfo.roomtitle}</td>
					</tr>
					<tr>
						<td>객실크기(평)</td>
						<td>${detailInfo.roomsize1}</td>
					</tr>
					<tr>
						<td>객실수</td>
						<td>${detailInfo.roomcount}</td>
					</tr>
					<tr>
						<td>기준인원</td>
						<td>${detailInfo.roombasecount}</td>
					</tr>
					<tr>
						<td>최대인원</td>
						<td>${detailInfo.roommaxcount}</td>
					</tr>
					<tr>
						<td>비수기주중최소</td>
						<td>${detailInfo.roomoffseasonminfee1}</td>
					</tr>
					<tr>
						<td>비수기주말최소</td>
						<td>${detailInfo.roomoffseasonminfee2}</td>
					</tr>
					<tr>
						<td>성수기주중최소</td>
						<td>${detailInfo.roompeakseasonminfee1}</td>
					</tr>
					<tr>
						<td>성수기주말최소</td>
						<td>${detailInfo.roompeakseasonminfee2}</td>
					</tr>
					<tr>
						<td>객실소개</td>
						<td>${detailInfo.roomintro}</td>
					</tr>
					<tr>
						<td>목욕시설</td>
						<td>${detailInfo.roombathfacility}</td>
					</tr>
					<tr>
						<td>욕조</td>
						<td>${detailInfo.roombath}</td>
					</tr>
					<tr>
						<td>홈시어터</td>
						<td>${detailInfo.roomhometheater}</td>
					</tr>
					<tr>
						<td>에어컨</td>
						<td>${detailInfo.roomaircondition}</td>
					</tr>
					<tr>
						<td>TV</td>
						<td>${detailInfo.roomtv}</td>
					</tr>
					<tr>
						<td>PC</td>
						<td>${detailInfo.roompc}</td>
					</tr>
					<tr>
						<td>케이블설치</td>
						<td>${detailInfo.roomcable}</td>
					</tr>
					<tr>
						<td>인터넷</td>
						<td>${detailInfo.roominternet}</td>
					</tr>
					<tr>
						<td>냉장고</td>
						<td>${detailInfo.roomrefrigerator}</td>
					</tr>
					<tr>
						<td>세면도구</td>
						<td>${detailInfo.roomtoiletries}</td>
					</tr>
					<tr>
						<td>소파</td>
						<td>${detailInfo.roomsofa}</td>
					</tr>
					<tr>
						<td>취사용품</td>
						<td>${detailInfo.roomcook}</td>
					</tr>
					<tr>
						<td>테이블</td>
						<td>${detailInfo.roomTable}</td>
					</tr>
					<tr>
						<td>드라이기</td>
						<td>${detailInfo.roomhairdryer}</td>
					</tr>
					<tr>
						<td>객실크기(평방미터)</td>
						<td>${detailInfo.roomsize2}</td>
					</tr>
					<tr>
						<td>객실사진1</td>
						<td><img alt="${detailInfo.roomimg1alt}" src="${detailInfo.roomimg1}"> </td>
					</tr>
					<tr>
						<td>객실사진2</td>
						<td><img alt="${detailInfo.roomimg2alt}" src="${detailInfo.roomimg2}"> </td>
					</tr>
					<tr>
						<td>객실사진3</td>
						<td><img alt="${detailInfo.roomimg3alt}" src="${detailInfo.roomimg3}"> </td>
					</tr>
					<tr>
						<td>객실사진4</td>
						<td><img alt="${detailInfo.roomimg4alt}" src="${detailInfo.roomimg4}"> </td>
					</tr>
					<tr>
						<td>객실사진5</td>
						<td><img alt="${detailInfo.roomimg5alt}" src="${detailInfo.roomimg5}"> </td>
					</tr>
			</c:when>
		</c:choose>
	</table>
</div>
